### ISSUE TITLE
Canceling out travel-related utility score?

### ISSUE THREAD

**Issue by gkmurthy10** [matsim-eth/av#55]
https://github.com/matsim-eth/av/blob/4eed78bcc119267dc19d70213cb43d2324812368/src/main/java/ch/ethz/matsim/av/scoring/AVScoringFunction.java#L89

You store the waiting time separately (unlike how waiting for pt is calculated in core) so I don't think you should be subtracting the marginal disutility of travel. What do you think?

Krishna

**Comment by sebhoerl** [comment]
Travel time is scored by the standard MATSim scoring function, which runs in parallel. That's why it needs to be substracted.
