### ISSUE TITLE
RunRobotaxiExample compatibility issues

### ISSUE THREAD

**Issue by mydingCCA** [matsim-eth/av#58]
Hi Guys,

I hvae recently tried the RunRobotaxiExample.java, the first time it runs fine.

Then I replaced the example network.gz and population file with my own, and the IDE gives NullPointerException in taxi modules which is another extension from MATSim.

Is there some other files that I should fix?

Best Regards,
Mike

**Comment by sebhoerl** [comment]
- Are you trying to run in parallel with the taxi contrib? Not sure that this works.
- If not, try to remove everything from the config that is related to taxi.
